### ISSUE TITLE
Watermarked videos are not the right format

### ISSUE THREAD

**Issue by mccalluc** [WGBH/stock-sales-2#131]
I get errors like this:
> HTTP "Content-Type" of "video/quicktime" is not supported. Load of media resource https://s3.amazonaws.com/wgbhstocksales.org/content/watermarked_clips/GBH00000012001044.mov failed.

@Muraszko : I'm guessing S3 guesses the MIME to send based on the extension. Do these all need to be reencoded, or is there any way we could get by with a name change?

**Comment by Muraszko** [comment]
Closing, watermarked versions are only for users to download.  Not for video playback.
