### ISSUE TITLE
Set content-disposition header on watermarked files

### ISSUE THREAD

**Issue by mccalluc** [WGBH/stock-sales-2#132]
We want the browser to just download these instead of trying to play them. I think this header can be set in S3. See if it can be set as default for directory, or scripted.

**Comment by mccalluc** [comment]
@afred: There are a few different approaches. Thoughts?
- (A) Make a script using the AWS S3 SDK that with set the content-disposition metadata for all these files. This will be a bit of a maintenance headache. The header can also be set per file, but if you miss it on one, it's hard to notice.
- We can tell S3 which headers to send on the response by setting query parameters on the url, and then signing the url ([java](http://docs.aws.amazon.com/AmazonS3/latest/dev/ShareObjectPreSignedURLJavaSDK.html), haven't found it in ruby sdk yet), either at
  - (B) ingest time, and storing the signed urls.
  - (C) or generating them at render time.

I'm leaning towards B, sign the urls at ingest time, but could be persuaded.

**Comment by mccalluc** [comment]
Go with (B). (C) is also good, but I worry a little bit about priv escalation.

**Comment by mccalluc** [comment]
Actually, (C). [SDK docs](http://docs.aws.amazon.com/sdkforruby/api/Aws/S3/Presigner.html):
>
Raises an ArgumentError if `:expires_in` exceeds one week. 

I don't think weekly refreshes are something we want to commit to, so the URLs will need to be signed in rails.

**Comment by afred** [comment]
@mccalluc cool. But how do we specify content-disposition?
