### ISSUE TITLE
Spec and implement empty search / search fail handling

### ISSUE THREAD

**Issue by mccalluc** [WGBH/stock-sales-2#139]
What should the behavior be
- if the user hits return in an empty search box, or chops the URL back to just `catalog`? 
- or if there are search terms, but there are no results?

Options:
- Redirect back to the homepage. (But that might not be where you came from.)
- Replace '' with '*' and return everything
- Bare error page with the only the message: "No results found for your search."
- Treat the same as the search error page (which itself is TBD)
- Suggest some common searches
- Pre-search validation: if the search field is empty, blink, but do not submit form.
- Pass over to Design

@AlisonCSmith : Please set direction and assign to me when it's ready to implement.

**Comment by AlisonCSmith** [comment]
:+1:

**Comment by mccalluc** [comment]
ie: no results is almost good enough as it. Prompt to enter a search if search empty.
