### ISSUE TITLE
move libraries from script dir to lib dir?

### ISSUE THREAD

**Issue by afred** [WGBH/stock-sales-2#147]
@mccalluc is there a reason for putting libraries unders `script/lib` instead of just `lib`? Do you have any object to doing this?..
  1. `mv scripts/lib/converter.rb scripts/lib/ingester.rb scripts/lib/log_roller.rb`
  1. `rm -r scripts`
  1. `mkdir spec/lib && mv spec/scripts/* spec/lib`

**Comment by mccalluc** [comment]
@afred: Think you mean `mv scripts/lib/* lib`?

These aren't run-time dependencies, and I guess I wanted to keep them in a place where that would be clear. Not something I feel strongly about, though if we change it here, I'd also like it to be changed in AAPB, just so we have some consistent patterns across our projects.

**Comment by mccalluc** [comment]
@afred: I'm going to close this, but feel free to reopen if my argument isn't convincing, or if there's another alternative.
