### ISSUE TITLE
move terms+conditions above copy-right in footer

### ISSUE THREAD

**Issue by mccalluc** [WGBH/stock-sales-2#148]

**Comment by mccalluc** [comment]
@AlisonCSmith : please confirm that this is what you want to see in the footer.

![screen shot 2015-10-16 at 10 36 37 am](https://cloud.githubusercontent.com/assets/730388/10544526/d9332220-73f1-11e5-8ec0-d16f8623b26c.png)

**Comment by mccalluc** [comment]
@AlisonCSmith : please confirm this is what you want.

**Comment by AlisonCSmith** [comment]
yes that looks good.  Tx
