### ISSUE TITLE
search for horse: thumbnails missing

### ISSUE THREAD

**Issue by mccalluc** [WGBH/stock-sales-2#149]

**Comment by mccalluc** [comment]
These items don't have Ci IDs in the current FM database. Earlier exports were not limited to items with Ci IDs, and we're not purging before each ingest. 

@afred: doing a purge before each ingest would fix this... but it's also a little risky. I'd lean towards treating this as a maintenance issue, but could be persuaded that the script should start with a clean slate. Thoughts?

**Comment by afred** [comment]
@mccalluc not in favor of purging. This seems like maintenance, and on-off maintenance at that.

**Comment by afred** [comment]
@mccalluc not seeing records with missing ci ids in solr

```ruby
# on production
solr.select(params: {q: "*:*"})['response']['numFound']
=> 11473
docs = solr.select(params: {q: "*:*", rows: 11473})['response']['docs']; nil
=> nil
docs.count
=> 11473
missing_ci_ids = docs.select { |doc|  ci_id = JSON.parse(doc['json']); (ci_id.nil? || ci_id == '') }
=> []
```

I assumed that Ci IDs missing from FM, combined with not checking for them, resulted in missing Ci IDs in the Solr index, which resulted in the missing thumbnails. Am I mistaken?

**Comment by afred** [comment]
^ ah.. nm.. i'm not getting the right `ci_id`.

**Comment by afred** [comment]
```ruby
solr = Solr.instance.connect
num_found = solr.select(params: {q: "*:*"})['response']['numFound']
docs = solr.select(params: {q: "*:*", rows: num_found})['response']['docs']
docs_missing_ci_ids = docs.select{ |doc| ci_id = JSON.parse(doc['json'])['ci_id']; ci_id == '' }
docs_missing_ci_ids.count
=> 3181
docs_missing_ci_ids.each { |doc| solr.}
```

**Comment by mccalluc** [comment]
@afred: I just blew away the index and reindexed. Your way probably would work, too, though I never want to feel like I need to maintain a solr index instead of being able to recreate it from scratch.
