### ISSUE TITLE
Search form for searching affiliated sites

### ISSUE THREAD

**Issue by afred** [WGBH/stock-sales-2#16]
**Done when**
User enters search terms, clicks a button, and a new tab is opened to affiliate site with search results for those terms.

**Comment by AlisonCSmith** [comment]
Here are the URL's for the various sites:
NOVA:  http://www.pbs.org/wgbh/nova/
Frontline:  
http://www.pbs.org/wgbh/pages/frontline/
American Experience:
http://www.pbs.org/wgbh/americanexperience/
Open Vault
http://openvault.wgbh.org/
AAPB:
http://americanarchive.org/

**Comment by mccalluc** [comment]
Just checked `SS_comp_collect8B.jpg`: Search-on-another-site is not something in the final mockups, though we had discussed it earlier. @AlisonCSmith: Let us know if this is mistaken. Closing.
