### ISSUE TITLE
Proposal: just skip call-to-action header in md width

### ISSUE THREAD

**Issue by mccalluc** [WGBH/stock-sales-2#164]
@AlisonCSmith : How would you feel about this when the window isn't full width?

![screen shot 2015-10-16 at 12 12 19 pm](https://cloud.githubusercontent.com/assets/730388/10546976/691e4c90-73ff-11e5-8a5c-43ccbe64e6f2.png)

By skipping the header we can get the height of the hero-video and the call-to-action sidebar nearly the same. This would only apply in this narrower width.

**Comment by afred** [comment]
:+1: (from @AlisonCSmith)
