### ISSUE TITLE
details page: smaller video

### ISSUE THREAD

**Issue by mccalluc** [WGBH/stock-sales-2#189]
- [x] make video 50/50 with metadata 
- [x] all metadata in right column
- [ ] no grey background on labels
- [ ]  25px padding bottom
- [ ] message about contact for licensing just below video. @AlisonCSmith will specify.

**Comment by afred** [comment]
@mccalluc and I think it might be better to keep the gray backgrounds on the field lables now that they are bunched over on the right.

What do you think @AlisonCSmith? Click the images to enlarge and get a truer feel...

**With the gray backgrounds**
![image](https://cloud.githubusercontent.com/assets/1507490/10677512/e65ebd86-78da-11e5-9882-3ca0208c5d91.png)

**Without the gray background**
![image](https://cloud.githubusercontent.com/assets/1507490/10677527/fc61c808-78da-11e5-97bc-dbdfccdb8ee1.png)

**Comment by afred** [comment]
@mccalluc where does the 25px bottom padding go?

**Comment by mccalluc** [comment]
@afred: I think it was between the items, but really I think what it is alread... though if we go without the background, maybe close up the space a little?

**Comment by mccalluc** [comment]
Good enough for now. Tweaks can be filed as-needed.
