### ISSUE TITLE
Search results mobile UX: What should thumbnail click do?

### ISSUE THREAD

**Issue by mccalluc** [WGBH/stock-sales-2#197]
Right now, clicking on the thumbnail will start or pause the video, because I wanted to offer this on devices that didn't have hover... but maybe the right thing is for it to be a link, so it's more like the collection thumbnails. Not sure. 

Thoughts?

**Comment by afred** [comment]
making it a link makes sense to me. @AlisonCSmith?

@mccalluc would it be crazy to emulate a "hover" on mobile by starting playback when video is a certain distance from the top of the view port? I've never seen this before, but it was just a thought. Also, not to be considered for soft launch :)

**Comment by mccalluc** [comment]
@afred: At least in the past on idevices video just wouldn't play unless the user explicitly initiated it, the idea being to avoid unnecessary bandwidth charges.

@AlisonCSmith : going to go ahead with this: particularly on smaller screens I think we need a larger click target.

**Comment by afred** [comment]
:+1:
