### ISSUE TITLE
Vertical-align content inside the .well classes to the middle

### ISSUE THREAD

**Issue by afred** [WGBH/stock-sales-2#201]
Here's [a resource on how to do this](https://css-tricks.com/centering-css-complete-guide/)

**Comment by mccalluc** [comment]
This is a regression. Content of wells was being vertically aligned [a few commits back](https://github.com/WGBH/stock-sales-2/pull/167). Lots of stuff has changed between then and now, but I'll see if I can get it working like it did before.

(current left; old pr right)
![screen shot 2015-10-23 at 11 38 35 am](https://cloud.githubusercontent.com/assets/730388/10697657/0e2826a4-797b-11e5-99b0-5686d9ec9c89.png)

**Comment by afred** [comment]
@mccalluc yes, it was a knowing regression by me. The problem with the style before was that it was reaching inside of the `.well` classes to affect individual components therein. In other words, the style of well contents was determined by it's existence within the well, which is a tight coupling that was causing me problems when I was trying get a consistent style of the search form in all places, whether it was in a `.well` or not.

In general, I'm trying to move toward keeping component design agnostic of it's context, as much as possible. I think the link above points to a strategy for being able to center elements vertically, while not having to know anything about what's inside of those elements.

**Comment by mccalluc** [comment]
Arrow / magnifier sizing is a separate issue, as is the padding above and below. Considering this fixed.
