### ISSUE TITLE
In travis.yml, why is secure given twice?

### ISSUE THREAD

**Issue by mccalluc** [WGBH/stock-sales-2#205]
And more generally, a comment pointing out how to regenerate this would be useful.

**Comment by afred** [comment]
@mccalluc i sent you an email explaining this. Is that sufficient, or did you want documentation within the `.travis.yml` file itself? I figured if we could get away without publicly explaining exactly what our secure env vars were, that would be better.

**Comment by mccalluc** [comment]
@afred: I remain uncomfortable with this. The name of the variable we've encrypted seems like the least of our problems if there actually were a leak, and if I or someone else is trying to figure out what these lines mean, I don't think it will necessarily occur to us to check old emails. But just my opinion.

**Comment by afred** [comment]
@mccalluc agreed. :+1: for annotating encrypted env vars in Travis
