### ISSUE TITLE
Equitable call to action icons

### ISSUE THREAD

**Issue by mccalluc** [WGBH/stock-sales-2#211]
See below: The arrows should be smaller, and the magnifier larger. (But the magnifier shouldn't be larger when it's just by itself.)
![screen shot 2015-10-27 at 9 56 00 am](https://cloud.githubusercontent.com/assets/730388/10760106/440dd7f0-7c91-11e5-85d8-bbedaca193e0.png)

**Comment by afred** [comment]
@mccalluc The magnifier is using `background-size: contain`, but it doesn't behave as cleanly as you would hope; changing the size of the containing element has other undesirable effects re: alignment. I would prefer it the images were simply the right size coming in.

**Comment by mccalluc** [comment]
hmm: The magnifier is actually 54px by 54px: The image should be big enough already. Investigating.

**Comment by mccalluc** [comment]
They are all the same, smaller, size now.
