### ISSUE TITLE
Consistent capitalization on homepage

### ISSUE THREAD

**Issue by mccalluc** [WGBH/stock-sales-2#219]
> Science & Technology: Video shorts, Interactives, Web Content, podcasts
> News & investigative reporting: Streaming programs, articles, video shorts, interviews
> American History, Timelines, Articles, Biographies, Maps

Probably capitalize only the first letter, though title case wouldn't be terrible. Let's just be consistent.

**Comment by afred** [comment]
i think @AlisonCSmith is this?

**Comment by mccalluc** [comment]
Well, I already fixed it to my taste in one of those unilateral PRs. It can be revisited if necessary.
