### ISSUE TITLE
Relative links as appropriate

### ISSUE THREAD

**Issue by mccalluc** [WGBH/stock-sales-2#223]
@lynnmason : just noticed that in 4f41aa92a214d you filled in URLs on the digital-clips page, which is great, except that we shouldn't use that form. Instead of 
```
http://54.161.5.56/catalog/GBH00275480000007
```
it should just be
```
/catalog/GBH00275480000007
```

(The numeric address isn't stable.)

**Comment by lynnmason** [comment]
OH!   I'll go back and fix then.

Lynn Mason|Stock Sales and Licensing
WGBH Media Library & Archives|One Guest Street
Boston, MA 02135
ph: 617-300-3909
fax: 617-300-1056
email:  lynn_mason@wgbh.org

Be sure to visit our website: www.wgbhstocksales.org
WGBH: The Power of Public Media

**Comment by mccalluc** [comment]
Those are fixed, and a quick check didn't reveal any other problems: 
```
grep -e '/catalog' -r app | grep -v openvault | grep -v bostonlocaltv | grep -v americanarchive | grep -v '(/catalog'
```
