### ISSUE TITLE
Add thumbnail images for collections to home page

### ISSUE THREAD

**Issue by afred** [WGBH/stock-sales-2#23]
**Done when**
Each collection on the home page is represented by an appropriate thumbnail image.

**Comment by Muraszko** [comment]
I'll be responsible for creating and delivering them to you guys.

**Comment by afred** [comment]
1. Nova
1. Frontline
1. American Experience
1. Openvault
1. In the news
1. AAPB
1. Boston
1. Digital Clips
1. Julia Child
1. WGBH Limited Series
1. Music
1. Sports

**Comment by mccalluc** [comment]
close in favor of #41
