### ISSUE TITLE
Remove top and left gutter on homepage call-to-action on widest screens

### ISSUE THREAD

**Issue by afred** [WGBH/stock-sales-2#262]
Done when:
  * bottom of call-to-action is flush with bottom of main video
  * there is no gutter to the top or left of the call to action

**Comment by mccalluc** [comment]
@afred: Just to be clear, this is a change from the original spec, right? Just concerned that if we start tweaks like this now, I'm not sure where it will end.

**Comment by afred** [comment]
@mccalluc yes, it is a change from the orig spec. See comments on #263, which is related.

**Comment by mccalluc** [comment]
Fixed by #302.
