### ISSUE TITLE
Stack homepage call-to-action beneath main video at all breakpoints except widest

### ISSUE THREAD

**Issue by afred** [WGBH/stock-sales-2#263]
**Done when** narrowing browser below the widest breakpoint causes the homepage call-to-action to stack vertically, beneath the main video (as it currently does for the 2nd to widest breakpoint)

**Comment by mccalluc** [comment]
@afred: This is related to #262, right? I'm hesitant about diving into this, for the same reasons.

**Comment by afred** [comment]
@mccalluc yep, they are related.

This stems from the mis-alignment of the bottom edges of the call-to-action block and the main video.

At the widest screen, they are close, but off enough to be noticeable:
![image](https://cloud.githubusercontent.com/assets/1507490/11503501/f17924c4-980e-11e5-8aec-a931c25320ae.png)

Moving down one breakpoint, we lose the call-to-action header (presumably to save vertical space?) but it doesn't do much good, because the call-to-action still grows much taller than the neighboring video.

![image](https://cloud.githubusercontent.com/assets/1507490/11503396/68a4b2da-980e-11e5-8e28-400fce7c19ec.png)

This is going to be unavoidable given the amount of text for reach call-to-action button, so the solution we came up with is to go to the vertically-stacked call-to-action at the 2nd-to-widest breakpoint.

**Comment by afred** [comment]
@mccalluc note that we can get pretty close just by using bootstrap's column classes. For instance, for the video column, use `col-lg-8 col-md-12` and for the call-to-action column, use `col-lg-4 col-md-12`.

It will take more tweaking than that, but I think that gives us close to the desired responsive behavior.

**Comment by mccalluc** [comment]
#302 also handled this. (Decided we could keep the sidebar in md after all.) Closing.
