### ISSUE TITLE
Add "Privacy Policy" and "Terms & Conditions" links to the other footer links

### ISSUE THREAD

**Issue by afred** [WGBH/stock-sales-2#269]
**Done when** "Privacy Policy" and "Terms & Conditions" are added to the end of the list of footer links

**Comment by mccalluc** [comment]
@afred: Can you confirm that we want to go from 
>
ABOUT US   |   RATES & POLICIES   |   FAQ   |   HOW TO LICENSE   |   CONTACT US
>
>
Privacy Policy | Terms & Conditions
Copyright 2015 WGBH Educational Foundation. All rights reserved.

to 

>
ABOUT US   |   RATES & POLICIES   |   FAQ   |   HOW TO LICENSE   |   CONTACT US |  PRIVACY POLICY  | TERMS & CONDITIONS
>
>
Copyright 2015 WGBH Educational Foundation. All rights reserved.

?

To me, this doesn't seem to be an improvement.
- The line of all-caps is just overwhelming.
- If you actually are looking for links to the legalese, it's objectively harder to find.

**Comment by afred** [comment]
@mccalluc confirmed. What @lwei definitely wanted was more spacing above the Copyright. We figured we could get the desired separation if we just moved all the links together into the footer menu. My (very weak) opinion is that the change looks cleaner, I showed them what it looks like and got a thumbs up.

**Comment by mccalluc** [comment]
okey-dokey,
