### ISSUE TITLE
Consistent drop-down control styling across browsers

### ISSUE THREAD

**Issue by afred** [WGBH/stock-sales-2#270]
Lei noticed that Firefox's dropdown buttons are not as pretty as they are in Chrome or Safari. I think we should stick with browser defaults. I'm holding out for further consideration

**Comment by mccalluc** [comment]
I would really, really prefer not to touch this:
no real benefit to user + a bit of work + more fragile.

**Comment by mccalluc** [comment]
Duplicates #91
