### ISSUE TITLE
Hide "Helpful Links" header when there are no links

### ISSUE THREAD

**Issue by afred** [WGBH/stock-sales-2#272]
**Done when** the "Helpful Links" header is hidden for all pages that do not have any links in that section.

**Comment by mccalluc** [comment]
@afred: In this case, should the main content also expand to fill the whole space? I'm not sure that it should, but wanted to raise the issue.

**Comment by afred** [comment]
@mccalluc the screens we were looking at had another element above the **Helpful Links**, a drop down, IIRC.

If there are cases where there there is nothing remaining to the right of the main content, then I dunno... ask @lwei?

**Comment by lwei** [comment]
@afred @mccalluc do not expand the content column on the left even if there is nothing remaining in the right col. Thanks!
