### ISSUE TITLE
Put search box on Collection pages inside white box (i.e. a "well") similar to the call-to-action

### ISSUE THREAD

**Issue by afred** [WGBH/stock-sales-2#273]
**Done when** the search box on the collection pages is contained within a white box (similar to as in call-to-action section) that aligns with the "Browse collections" drop down above it.

**Comment by mccalluc** [comment]
(Want to wait on coming back to this until #304 is merged: Both go into the CSS.)

**Comment by mccalluc** [comment]
@afred: Re-reading this, it struck me that only one collection page has a search box: The clips collection. I'm interpreting this bug to mean that we want a white box on the entire sidebar, just as we have a bluebox on the sidebar on the other pages.

**Comment by afred** [comment]
I think the intent was something like this...

![image](https://cloud.githubusercontent.com/assets/1507490/11632057/41a4b99a-9cd3-11e5-911a-944b8bd3c0c1.png)

 confirm @lwei? @AlisonCSmith?

**Comment by lwei** [comment]
@afred yes, that's correct except that the background color should be white (#fff) instead of a light grey. Thanks!
