### ISSUE TITLE
Darken default link color of search result titles

### ISSUE THREAD

**Issue by afred** [WGBH/stock-sales-2#274]
**Done when** default link color of search results titles is the same as it's current :hover state.

**Comment by mccalluc** [comment]
@afred: Do we actually want to change link color across the board? Right now, it's getting that shade of blue from bootstrap. Should the links on /about/faq (for example) also be darker? I'm reluctant to make it so different links in different contexts get different colors.

**Comment by afred** [comment]
@mccalluc the goal is to avoid the color change on hover. Just stick with the darker of the two blues. Ticket #264 is the same issue.

Not sure if @lwei wanted to do this across the board or not.

**Comment by afred** [comment]
@mccalluc ... but I would say :+1: to changing FAQ and Helpful Links too. I think the idea is to _either_ change color _OR_ underline on `a:hover`, but not both.

**Comment by lwei** [comment]
@afred yes, change the link color across the board, except the top and footer nav links. Thanks!
