### ISSUE TITLE
Watermarked video download needs to contain the GBH id number

### ISSUE THREAD

**Issue by afred** [WGBH/stock-sales-2#276]
**Done when** watermarked videos contain the GBH id number in the downloaded filename

**Comment by Muraszko** [comment]
The watermarked video files are hosted on S3 with the GBH ID as their file names.  Are they being renamed when downloaded?

**Comment by afred** [comment]
i thought it was weird if we had changed the names. This will take a little peeking

**Comment by mccalluc** [comment]
The filename is coming from the HTTP header we ask AWS to provide:
```ruby
class DownloadsController < AwsRedirectController
  def extra_params
    {response_content_disposition: "attachment; filename=wgbh-stock-sales.mov"}
  end
end
```

**Comment by afred** [comment]
Super. Should be an easy change then. But what should it be? Some options:

1. "GBH00128384000004.mov" (is ID-only sufficient? Not very user friendly)
1. "WGBH Stock Footage - GBH00128384000004.mov" (Is this too long?)
