### ISSUE TITLE
Change home top links

### ISSUE THREAD

**Issue by afred** [WGBH/stock-sales-2#28]
**Done when**
Menu items and contact info displays across the top as in this image.

@mccalluc notes: Latest mockups have two rows in header. Clarify desired end state, for different screen widths.

![ss_comp_home](https://cloud.githubusercontent.com/assets/1507490/9919198/402d446c-5c99-11e5-95fa-b5c345be7aee.jpg)

**Comment by mccalluc** [comment]
(Talked to Lisa: one row on home, two rows, plus logo on left on others.)

**Comment by mccalluc** [comment]
Banner looks good. Exactly what to do for slightly narrower widths is under-specified, but refinements can be filed separately.
