### ISSUE TITLE
Change "contact us" message on search results page

### ISSUE THREAD

**Issue by afred** [WGBH/stock-sales-2#282]
**Done when**
  * verbiage on search results page is changed from "Didn't find what you were looking for? Please contact us!" to "Can’t find it online?  Contact us!"
  * style is changed thusly: `font-size: 20px; font-weight: 500;`, and the message is centered with respect to the search results below.

make it look like this (per conversation with @AlisonCSmith)
![image](https://cloud.githubusercontent.com/assets/1507490/11403082/0ae9efce-9369-11e5-894c-9abe4c654a13.png)

**Comment by mccalluc** [comment]
Fixed by #290.
