### ISSUE TITLE
Home page hero image and primary call to action

### ISSUE THREAD

**Issue by afred** [WGBH/stock-sales-2#29]
**Done when**
  * Hero image is added, aligned, and sized correctly according to image below.
  * Primary calls to action are added and styled according to image below.

![ss_comp_home](https://cloud.githubusercontent.com/assets/1507490/9919247/9532db52-5c99-11e5-883b-1cc6bcc403ff.jpg)

**Comment by Muraszko** [comment]
@afred The hero image is actually going to be a moving image without sound, sort of like a clip reel.  I'll keep the size the same as if it were the planned hero image.

**Comment by mccalluc** [comment]
Put a placeholder in for the hero. New bug #46 to get video. Sidebar looks ok.
