### ISSUE TITLE
Reduce font in the WGBH Stock Sales logo

### ISSUE THREAD

**Issue by AlisonCSmith** [WGBH/stock-sales-2#305]
As per Li's comments, please reduce the font size for the "Stock Sales and LIcensing" part
of the home page logo which is currently too large: 

The Stock Sales brand logo on the homepage should be smaller. Some specs:
Height of the logo image = 78 px (currently 123 px)
Height of the blue header = 128 px

**Comment by mccalluc** [comment]
Duplicates #309
