### ISSUE TITLE
Resize homepage logo

### ISSUE THREAD

**Issue by mccalluc** [WGBH/stock-sales-2#309]
>
The Stock Sales brand logo on the homepage should be smaller. Some specs:
    Height of the logo image = 78 px (currently 123 px)
    Height of the blue header = 128 px

**Comment by mccalluc** [comment]
I think this needs to be thought through. 
- Making the logo that small in full screen mode means it only spans a third of the page width, which doesn't seem right.
- Is this supposed to change with different screen widths?
- If we make the blue header shorter, how does the italicized text to the right respond? Does it get a smaller margin? Smaller text? Smaller line spacing?

If anything needs to change here, we need to tweak the html in the inspector and make sure the end result is good in all widths.

**Comment by AlisonCSmith** [comment]
What is the size now?  Is it possible to reduce it 2 points? (e.g. if it's 24 can we go down to 22?)
Alison
