### ISSUE TITLE
Make sure fonts work

### ISSUE THREAD

**Issue by mccalluc** [WGBH/stock-sales-2#35]
Two things:
- Do you just reference http://www.wgbh.org/css/fonts.css in our html, or is it more complicated than that?
- Do we have the appropriate licence?

On the second point: I was expecting a setup where referer headers are checked, and content is only sent if it matches a white list... but that doesn't seem to be the case.

```
$ curl -s 'http://www.wgbh.org/css/fonts.css' | less
/*
        Copyright (C) 2011-2014 Hoefler & Co.
        ....
*/
@font-face{ font-family: "Whitney SSm A"; src: url(data:application/x-font-woff;base64,d09GRk9UVE8AADYNAA0AAAAAXYgAAQAAAAA...
```

Fonts are being served with or without the referer -- Without seeing an access denied, I'm not confident that we actually have been granted reliable access.

**Comment by tim-wgbh** [comment]
Hi, Tim Kinnel here. Teri asked me to check into this for you. I have added wgbhstocksales.org.
You'll need to add this to the header:

    <link rel="stylesheet" type="text/css" href="//cloud.typography.com/7419092/724404/css/fonts.css" />

Font declarations are then:
_Whitney Book_
    font-family: "Whitney SSm A", "Whitney SSm B";
    font-style: normal;
    font-weight: 400;

_Whitney Book Italic_

     font-family: "Whitney SSm A", "Whitney SSm B";
     font-style: italic;
     font-weight: 400;

_Whitney Bold_

     font-family: "Whitney SSm A", "Whitney SSm B";
     font-style: normal;
     font-weight: 700;

_Whitney Bold Italic_

     font-family: "Whitney SSm A", "Whitney SSm B";
     font-style: italic;
     font-weight: 700;

**Comment by mccalluc** [comment]
@tim-wgbh: awesome: I set wgbhstocksales.org to 128.0.0.1 in hosts, and I get all the Whitneys.... Li's design also calls for "Minion Pro": Can you also set us up with that? Let me know if there's any other info you need.

```
perl -pne 's/;/;\n/g' ~/Desktop/font.css | grep font-family
@font-face{ font-family: "Whitney SSm A";
 } @font-face{ font-family: "Whitney SSm B";
 } @font-face{ font-family: "Whitney SSm A";
 } @font-face{ font-family: "Whitney SSm B";
 } @font-face{ font-family: "Whitney SSm A";
 } @font-face{ font-family: "Whitney SSm B";
 } @font-face{ font-family: "Whitney SSm A";
 } @font-face{ font-family: "Whitney SSm B";
```

**Comment by tim-wgbh** [comment]
Whitney is licensed through Hoeffler (typography.com<http://typography.com>). Minion Pro is licensed  Adobe Typekit. I don't know how you would want to handle that, Teri.

I did a little research and, alternatively, there is a font called Crimson on fontsquirrel.com<http://fontsquirrel.com> which is very similar to Minion Pro and which can be used for free.

I have used fontsquirrel on a number of projects, including cravingboston.wgbh.org<http://cravingboston.wgbh.org>, and I really like it as a resource.

Best regards,
Tim


On Sep 17, 2015, at 5:55 PM, mccalluc <notifications@github.com<mailto:notifications@github.com>> wrote:


@tim-wgbh<https://github.com/tim-wgbh>: awesome: I set wgbhstocksales.org<http://wgbhstocksales.org> to 128.0.0.1 in hosts, and I get all the Whitneys.... Li's design also calls for "Minion Pro": Can you also set us up with that? Let me know if there's any other info you need.

perl -pne 's/;/;\n/g' ~/Desktop/font.css | grep font-family
@font-face{ font-family: "Whitney SSm A";
 } @font-face{ font-family: "Whitney SSm B";
 } @font-face{ font-family: "Whitney SSm A";
 } @font-face{ font-family: "Whitney SSm B";
 } @font-face{ font-family: "Whitney SSm A";
 } @font-face{ font-family: "Whitney SSm B";
 } @font-face{ font-family: "Whitney SSm A";
 } @font-face{ font-family: "Whitney SSm B";

**Comment by mccalluc** [comment]
@tim-wgbh : Thanks! That will work.

Still working though issues, but that's on our side. Right now: inspector says it's Whitney... but it doesn't look that way to me? Probably doing something dumb. TODO
![screen shot 2015-09-18 at 12 15 14 pm](https://cloud.githubusercontent.com/assets/730388/9964582/2171b62c-5dff-11e5-8408-10aeb537575a.png)

**Comment by tim-wgbh** [comment]
There are browser extensions like FontFinder or WhatFont for both Chrome and Firefox. They'll tell you what font is actually being rendered.

**Comment by tim-wgbh** [comment]
The font family declaration has to match what is specified in the font-face declarations:

@font-face...

So this must be declared as "font-family: "Whitney SSm A", "Whitney SSm B";

In the CSS. Don't ask me why you have to declare both A and B....

[screen shot 2015-09-18 at 12 15 14 pm]<https://cloud.githubusercontent.com/assets/730388/9964582/2171b62c-5dff-11e5-8408-10aeb537575a.png>

-

**Comment by mccalluc** [comment]
(Ended up gettting Crimson Text from google web fonts.)
