### ISSUE TITLE
Add images to the Collection pages

### ISSUE THREAD

**Issue by Muraszko** [WGBH/stock-sales-2#41]
Done when all the collection pages have the image files on S3 and are verified to be on the website.

(Splash and Logo are optional... but we need to distinguish an explicit decision from "oh, we didn't get around to it.")

To get a list from S3:
```
$ aws s3 ls --recursive wgbhstocksales.org/content | grep -v '/$'
```

- **NOVA**
 - [x] [Homepage thumb](https://s3.amazonaws.com/wgbhstocksales.org/content/collections/nova/nova-thumb_348x196.png)
 - [x] [Splash](https://s3.amazonaws.com/wgbhstocksales.org/content/collections/nova/nova_collection_main_770x433.png)
 - [x] [Logo w/ alpha](https://s3.amazonaws.com/wgbhstocksales.org/content/collections/nova/nova-logo.png)
 - [x] Thumb1
 - [x] Thumb2
 - [x] Thumb3
 - [x] Thumb4
 - [x] Thumb5
 - [x] Thumb6

- **Frontline**
 - [x] [Homepage thumb](https://s3.amazonaws.com/wgbhstocksales.org/content/collections/frontline/frontline-thumb_348x196.png)
 - [x] [Splash](https://s3.amazonaws.com/wgbhstocksales.org/content/collections/fronline/fronline_collection_main_770x433.png)
 - [x] [Logo w/ alpha](https://s3.amazonaws.com/wgbhstocksales.org/content/collections/frontline/frontline-logo.png)
 - [x] Thumb1
 - [x] Thumb2
 - [x] Thumb3
 - [x] Thumb4
 - [x] Thumb5
 - [x] Thumb6

- **AMEX**
 - [x] [Homepage thumb](	
https://s3.amazonaws.com/wgbhstocksales.org/content/collections/amex/amex-thumb.png)
 - [x] Splash
 - [x] [Logo w/ alpha](https://s3.amazonaws.com/wgbhstocksales.org/content/collections/amex/amex-logo.png)
 - [x] Thumb1
 - [x] Thumb2
 - [x] Thumb3
 - [x] Thumb4
 - [x] Thumb5
 - [x] Thumb6

- **Open Vault**
 - [x] Homepage thumb
 - [x] Splash
 - [ ] Logo w/ alpha
 - [x] Thumb1
 - [x] Thumb2
 - [x] Thumb3
 - [x] Thumb4
 - [x] Thumb5
 - [x] Thumb6

- **In The News**
 - [x] Homepage thumb
 - [ ] Splash (MAYBE VIDEO?)
 - **NO LOGO**
 - [ ] Thumb1
 - [ ] Thumb2
 - [ ] Thumb3
 - [ ] Thumb1
 - [ ] Thumb2
 - [ ] Thumb3

- **AAPB**
 - [x] Homepage thumb
 - [x] Splash
 - [ ] Logo w/ alpha
 - [x] Thumb1
 - [x] Thumb2
 - [x] Thumb3
 - [x] Thumb4
 - [x] Thumb5
 - [x] Thumb6

- **Boston**
 - [x] Homepage thumb
 - **NO SPLASH**
 - **NO LOGO**
 - [x] Thumb1
 - [x] Thumb2
 - [x] Thumb3
 - [x] Thumb4
 - [x] Thumb5
 - [x] Thumb6

- **Digital Clips**
 - [x] Homepage thumb
 - **NO SPLASH**
 - **NO LOGO**
 - [x] Thumb1
 - [x] Thumb2
 - [x] Thumb3
 - [x] Thumb4
 - [x] Thumb5
 - [x] Thumb6
 - [x] Thumb7
 - [x] Thumb8
 - [x] Thumb9

- **Julia Child**
 - [x] Homepage thumb
 - [x] [Splash](https://s3.amazonaws.com/wgbhstocksales.org/content/collections/julia_child/julia_collection_main_770x433.png)
 - **NO LOGO**
 - [x] Thumb1
 - [x] Thumb2
 - [x] Thumb3

- **WGBH Limited Series**
 - [x] Homepage thumb
 - **NO SPLASH**
 - **NO LOGO**
 - [x] Thumb1
 - [x] Thumb2
 - [x] Thumb3
 - [x] Thumb4
 - [x] Thumb5
 - [x] Thumb6

- **Music**
 - [x] Homepage thumb
 - **NO SPLASH**
 - **NO LOGO**
 - [x] Thumb1
 - [x] Thumb2
 - [x] Thumb3

- **Sports**
 - [x] Homepage thumb
 - **NO SPLASH**
 - **NO LOGO**
 - [x] Thumb1
 - [x] Thumb2
 - [x] Thumb3

**Comment by afred** [comment]
@AlisonCSmith is this checklist useful? If so, can we use it to track the progress of getting proper image URLs in place. If not, can we just close this ticket?

**Comment by afred** [comment]
I will run through this list with the latest from `master`

**Comment by afred** [comment]
there are 4 remaining items that I think we want to finish, but I made new tickets for them in #231, #234, #235, and #236. Closing this in favor of those.
