### ISSUE TITLE
Homepage hero loop

### ISSUE THREAD

**Issue by mccalluc** [WGBH/stock-sales-2#46]
Mike provides, and then we'll put it up: Not sure if videoJS wrapped is necessary... Maybe just a video element would suffice?

**Comment by Muraszko** [comment]
@mccalluc 
[Here is the S3 link to the video.](https://s3.amazonaws.com/wgbhstocksales.org/content/Sales_homepage_reel_10072015_1200Kbps_480p.mp4)

The size should fit the space allocated on the homepage.
