### ISSUE TITLE
Hover banner images need color change

### ISSUE THREAD

**Issue by mccalluc** [WGBH/stock-sales-2#49]
On hover we want the banner icons to change color just like the text. Just images right now. cf: http://stackoverflow.com/questions/7415872/change-color-of-png-image-via-css

options:
- add another white version of each
- esoteric CSS masking
- **use glyphicons**

Get buy-in before continuing.

**Comment by Muraszko** [comment]
+1 for glyphicons

**Comment by lisarosenthal** [comment]
Which banner icons are you referring to?

**Comment by mccalluc** [comment]
Fixed and deployed.
@lisarosenthal: telephone and envelope. If we want to tweak something, it might be to move them down a couple pixels, instead of sitting on the base line, but I think this is a good solution.

**Comment by lisarosenthal** [comment]
@mccalluc So is it too difficult to have the links on the left and the phone and email to the right on the full-width desktop view?
