### ISSUE TITLE
Larger logo in navbar + color change on hover

### ISSUE THREAD

**Issue by mccalluc** [WGBH/stock-sales-2#65]
A larger logo in the navbar has been requested. We're also going to want to change on the color on hover. That is annoying with graphics, and fragile.

Proposal: Use an embedded SVG
- styleable
- resizable
- recolorable

I think it will be easier to use https://en.wikipedia.org/wiki/File:WGBH_logo.svg and add "Stock Sales & Licensing" than to try to convert and EPS from the logofarm to SVG.

@afred: Sanity check?

**Comment by afred** [comment]
I'm not sure I agree (stylistically) with changing the logo on hover. That's kind of unusual, no?

Also, I'm not familiar with styling SVGs with CSS. I have, however, swapped out images on hover before, which is what we could do for the logo. It's not that complicated, but it does require having two images, correctly sized and colored.

I'd say do whatever is easier between:
  a) creating a new SVG with the "stock sales" treatment
  b) OR, create two logo versions, one for "regular" and another for "hover".

applying the style changes on hover would be roughly the same amount of work in either case, i would think.

**Comment by mccalluc** [comment]
@lisarosenthal : Will the logo up at the very top need to change color on hover the same way links do? Or does it just stay the same pale blue regardless?

**Comment by lisarosenthal** [comment]
@mccalluc Yes, see "logo_stock-sales_sml2hover.png" It's a very light blue (dee5f0) Also please note that the text links in the top nav should be #dee5f0 on hover and not #fff (white) please refer to the spec sheet. Thanks.

**Comment by afred** [comment]
@mccalluc @lisarosenthal where are the images and spec sheet to which you're referring?

**Comment by lisarosenthal** [comment]
@afred @mccalluc  Chuck I believe that Li sent you comps, deliverables, specs, and grid layouts, is that correct?

**Comment by Muraszko** [comment]
Here guys?
smb://deptfs.wgbh.org/dept/MLA/stock-sales-new/SS

**Comment by afred** [comment]
@Muraszko yeah ok, that's where I'm looking. I just don't see `logo_stock-sales_sml2hover.png`, but I _do_ see `logo_stock-sales_sml.png`. Maybe the hover img hasn't been uploaded yet?

**Comment by lisarosenthal** [comment]
I can't access this, but there may have been additional deliverable emailed to Chuck, he should have all the latest stuff. Let me know if you need me to redeliver anything.

**Comment by mccalluc** [comment]
Using the SVG currently: Seems to work for me, and haven't heard complaints from other corners.
