### ISSUE TITLE
Collection Landing Pages: grid spacing and design tweaks

### ISSUE THREAD

**Issue by lisarosenthal** [WGBH/stock-sales-2#81]
![boxes](https://cloud.githubusercontent.com/assets/14838427/10228301/d1d01ac8-683f-11e5-9c73-8ac5951a13eb.png)
![helpful-links](https://cloud.githubusercontent.com/assets/14838427/10228599/ab09b6fe-6841-11e5-859d-7ccfddf360d9.png)

• Collection pages need to have the same wider left/right margin in the content area as is on the home page
• See specs for "Helpful Links" styles 
• Double the vertical space between top of light blue background and start of content below
• Add vertical space between descriptive text and 3-across images below (30 px to match space between collection rows on home page)
• The "Need Help..." search boxes at bottom of page should have the same widths as the 3-across images above
• Height of those 3 boxes should have same top and bottom padding above text, see attached
• Equal space above/below search boxes of the light blue background, approx 30 px or match attached screen shot
• Still to be done: add Explore Collections search box

**Comment by mccalluc** [comment]
I believe with the latest deploy the spacing by and large matches the spec. Discrepancies can be filed individually.
