### ISSUE TITLE
Home page mobile/tablet design

### ISSUE THREAD

**Issue by lisarosenthal** [WGBH/stock-sales-2#83]
Can we make it so the "Need Help..." box with the three search boxes expands the fill width on mobile and tablet portrait? So it wouldn't have left margin padding.

On tablet portrait view the collection images and descriptions can be 2-across.

I'm also noticing that the collection description text has some hard line breaks that are showing up in table landscape view (3-across)

**Comment by mccalluc** [comment]
I think these are taken care of, except for the 2-across, which I think we decided against.
