### ISSUE TITLE
Is aspect ratio of main png logo correct?

### ISSUE THREAD

**Issue by mccalluc** [WGBH/stock-sales-2#85]
Comparing to wgbh homepage, it seems to be stretched:
![screen shot 2015-10-01 at 5 45 14 pm](https://cloud.githubusercontent.com/assets/730388/10234686/43344418-6864-11e5-9834-da8a62f384f5.png)

The SVG I've been working with matches the www.wgbh.org logo, *not* the PNG stock sales logo.

**Comment by Muraszko** [comment]
@mccalluc 
[I resized the logo png and put it on S3.](https://s3.amazonaws.com/wgbhstocksales.org/content/home_page/logo-big.png)
