### ISSUE TITLE
Figure out spec for font sizes.

### ISSUE THREAD

**Issue by mccalluc** [WGBH/stock-sales-2#93]
If I use the font sizes in the spec, the result is text that is much larger than in the mockups, so I've taken approximating the mockups as my primary goal. For example:

![screen shot 2015-10-02 at 3 34 45 pm](https://cloud.githubusercontent.com/assets/730388/10255953/be199540-691b-11e5-9cd2-7ed0560fc12a.png)
- The left is the current website; text is specified as 12px;
- The right is the mockup; According to Lisa's spec, this is 18px ... but obviously changing the current CSS to match the spec is not in the end going to produce a result that we want.

I don't actually see a problem here: Things mostly look ok, and individual exceptions can be identified and fixed. I don't have any idea right now about why we have such different ideas about how large 18px is supposed to be, but I'm ok with that being a mystery.

**Comment by lisarosenthal** [comment]
![screen shot 2015-10-02 at 3 52 36 pm](https://cloud.githubusercontent.com/assets/14838427/10256207/b08ee216-691d-11e5-9c46-95849244e226.png)
This is what I'm seeing with my browser view reset. Are you looking at the mockups at the correct size, or is you're browser set larger? I'm pretty certain that 12 px is too small.

**Comment by afred** [comment]
:+1: for "it's not really a problem". Changing font-size is quite easy.

but also,
:+1: for changing `.thumb { font-size: 18px; }`. I'm not sure what you're seeing @mccalluc, but I see the same thing as @lisarosenthal.

Here is my screen grab with `.thumb { font-size: 18px; }`. Obviously github resized the image, but notice the nice proportions.
![image](https://cloud.githubusercontent.com/assets/1507490/10256561/10ecc126-6920-11e5-947a-3afa97be462f.png)

**Comment by lisarosenthal** [comment]
@mccalluc I think maybe your looking at it at a smaller break point. At the larger view, full desktop, the font needs to be the larger size that I speced. Then we can either scale it down proportionally at the smaller breakpoints or not, as we see fit. The text probably needs to be smaller for mobile view.

**Comment by mccalluc** [comment]
(beat me to it: I was writing this:)

Ach: Ok, I know what's going on now: The ratio between the image rectangles and and the text size is different in the `md` and `lg` responsive layouts, and the screen shots I took were from `md`, and yours are `lg`. So I can apply the font sizes as spec'd, and will note here when that's done.

Lingering questions:
- How exactly do the short blurbs below the collections work? Originally, I had `<br>`s in there, but maybe it should flow naturally, and if it wraps to a third line, that's ok?
- Is the `md`/`lg` distinction actually something we need, or is it just confusing? Right we're dealing with four versions of the site, and maybe three would suffice. (Right now, in `md` the content is limited to 970px, and in `lg` that goes to 1230px.)
- We could also drop `lg`, and make `md` a little wider.

**Comment by afred** [comment]
@lisarosenthal i'm not certain we actually have to change font sizes when crossing breakpoints. I think modern devices handle it pretty gracefully. For instance, here's a screenshot from the Google Nexus 4 emulator that Chrome browser provides. Here the font-size in question is specified as `18px`.
![image](https://cloud.githubusercontent.com/assets/1507490/10256908/2dd73490-6922-11e5-8b4a-f145554f867d.png)

**Comment by lisarosenthal** [comment]
@afred Yes you're probably right, we can see if there are any exceptions, but hopefully it will be fine.
@mccalluc The description blurbs should flow naturally, right now there are some weird line breaks. As far as the break points go, not quite sure, maybe three would work, 1. large desktop (same as tablet landscape) 2. tablet portrait, and 3. mobile. I think I put in a few notes already in Github about changing tablet portrait view to 2-across for the collection thumbs on home page, etc.

**Comment by mccalluc** [comment]
These font sizes now match the spec. Closing.
