### ISSUE TITLE
Finalize contact-us google form

### ISSUE THREAD

**Issue by mccalluc** [WGBH/stock-sales-2#95]
@AlisonCSmith : Relating to the PR I just submitted (#94), you should now be the owner of Google form that will be used for the contact page. You'll need to decide what options you want on the form... In particular, what choices go in the pull down.

**Comment by AlisonCSmith** [comment]
okay!  Updating shortly.
Tx,
Alison

Alison Smith|Associate Director|Stock Sales and Licensing
WGBH Media Library & Archives|One Guest Street
Boston, MA 02135
ph: 617-300-3916
fax: 617-300-1056
email: alison_smith@wgbh.org

Be sure to visit our website: www.wgbhstocksales.org
WGBH: The Power of Public Media

**Comment by afred** [comment]
@AlisonCSmith when this is done, let us know in a comment here, or just close this PR using the buttons below. Thanks!
