### ISSUE TITLE
Resize all the S3 images

### ISSUE THREAD

**Issue by mccalluc** [WGBH/stock-sales-2#98]
I've just been uploading images to S3 in their original format, because I didn't want to under-size them and then have to redo the work... but for the sake of page load they should be sized appropriately. 

(... though, if we think they're really stable, we might go as far as compositing them so there's just one image load on the homepage, but that would probably be gratuitous.)

**Comment by Muraszko** [comment]
The ones I have been uploading are the correct size.
I deleted and uploaded resized versions of:
[Frontline Homepage] (https://s3.amazonaws.com/wgbhstocksales.org/content/collections/frontline/frontline-thumb_348x196.png)
[AMEX Homepage] (https://s3.amazonaws.com/wgbhstocksales.org/content/collections/amex/amex-thumb_348x196.png)
[NOVA Homepage] (https://s3.amazonaws.com/wgbhstocksales.org/content/collections/nova/nova-thumb_348x196.png)

Were there others?

**Comment by mccalluc** [comment]
@Muraszko : um, I think some links might have broken. For instance, [nova](https://github.com/WGBH/stock-sales-2/blob/master/app/views/collections/nova.md) has this markdown:
```md
![logo](https://s3.amazonaws.com/wgbhstocksales.org/content/collections/nova/nova-logo.png)
![thumb](https://s3.amazonaws.com/wgbhstocksales.org/content/collections/nova/nova-thumb.png)
![splash](https://s3.amazonaws.com/wgbhstocksales.org/content/collections/nova/nova_collection_main_770x433.png)
```

but [s3](https://console.aws.amazon.com/s3/home?region=us-east-1#&bucket=wgbhstocksales.org&prefix=content/collections/nova/) has `nova-thumb_348x196.png` -> filenames need to match, and I'm guessing this was your change?

Actually, that answers your other question, too: When the page is rendered on github, there's no sizing, so if it's much too large, it's obvious... but this really isn't a priority: I think if we do one pass at the end we're less likely to get confused, but your call. Thanks!

(I'm going to file a new bug for checking that all img links are good.)

**Comment by Muraszko** [comment]
I committed the S3 location changes to the master for those three.

**Comment by Muraszko** [comment]
I also found a un-resized image for Julia Child and Open Vault, so I resized and updated the master branch with the correct urls.  In the future I'll try and catch the created images before they get on S3 to verify the sizes.  I'll also update the branch with the correct URLs.
